### ISSUE TITLE
Team 22 Review: VnV Plan, test plan for NFR1 missing

### ISSUE THREAD

**Issue by RutheniumVI** [Dharakverma/vehicle_control_system#13]
While reading yor tests for non-functional requirements, I noticed that the test for NFR1 about the models following a standardized format not being tested. I understand that this is not straightforward to test but one way to test it can be having code review before the code for this model is merged. Another way can be to get a 3rd party stakeholder to go through the code and review the models based on standard.

**Comment by Dharakverma** [comment]
We will be requiring at minimum 2 approvals before code is merged. In that review process, the members have been instructed to look at format alongside functionality. Format is usually the easiest thing to catch in a PR.
