### ISSUE TITLE
Team 22 Review: Missing tests for some FRs

### ISSUE THREAD

**Issue by KevinRK29** [Dharakverma/vehicle_control_system#15]
Not all the FRs mentioned in the SRS are covered in the tests mentioned in the VnV plan. For example, for the several FRs under Cooling Control Ring in the SRS, there are no mention about it in the VnV plan and how they will be tested. One way to avoid this is to double check in the traceability matrix that all the FRs are there and being mapped to tests in the VnV plan

@samm82

**Comment by Dharakverma** [comment]
We specified in our VnV plan that some of the FR's found in our SRS document are no longer relevant due to major architectural changes to our control system. We will work to update our SRS document and keep it in line with the current architecture which we referenced in our VnV plan. Closing issue.
