### ISSUE TITLE
Implement driver interface logic

### ISSUE THREAD

**Issue by yangl56** [Dharakverma/vehicle_control_system#17]
- startup logic
- determine how we will read these signals from software (IO pin read?) - help from Dharak/Abhi
- pedal mapping LUT w linear interpol
- pedal signal error monitoring
- accel pedal sensor profiling/arbitration

**Comment by abhishekmagdum** [comment]
filtering of accelerator values done. Lookup table for curve works.

Just need to add steering angle sensor.
