### ISSUE TITLE
Team_24_Review

### ISSUE THREAD

**Issue by ramundis** [Dharakverma/vehicle_control_system#2]
SRS Review Team 28

SRS Issues:
1. Functional Requirement stating competition rules may be better suited as NFRs or constraints. These are not requirements of the system to function properly, but rather outline the parameters in which the system must adhere to for competition. For example, the system will still be able to meet scope if the maximum power drawn from the accumulator exceeds 80 kW
2. Readability of the document is impacted by some acronyms missing from 2.2: MD (mandated constraints), RF (relevant facts), UML (unified modelling language), AMR (accumulator management ring, assuming labelled incorrectly in 2.2), HV, RTDS, GLV. Acronyms listed should also be alphabetical.
3. Will the functionality of the vehicle control system be impacted by an addition or change in the EV’s electrical components? If yes, it should be stated as an assumption that electrical components will not be changing before competition. If no, this should be stated as a relevant fact and explained.
4. Non-Functional Requirement 2 would be better categorized as a Functional Requirement. When considering the issue of computing power, if this microcontroller must be used or else the system will have no compatibility then this is functional.
5. Since this project is being done in tandem with MFE, it felt as though many design decisions that have been externally imposed should have been listed as constraints, as per rubric. For example, the team-selected microcontroller (STM32F7)

**Comment by smiths** [comment]
@ramundis, next time, please create five separate issues.
