### ISSUE TITLE
Incorporate ready to drive speaker into the control system

### ISSUE THREAD

**Issue by Dharakverma** [Dharakverma/vehicle_control_system#24]
As per the rules, the ready to drive speaker should sound when the accelerator pedal will send torque commands to the motors. Since our control system is in charge of those commands, it should also be in charge of the ready to drive speaker.

**Comment by Rolyap-gh** [comment]
![image](https://user-images.githubusercontent.com/114005670/206602247-c110ac02-29e2-4e62-99bb-423924553494.png)

**Comment by Rolyap-gh** [comment]
Doneso
