### ISSUE TITLE
Team 23 Review: Hazard Analysis - Overlapping Safety Requirements

### ISSUE THREAD

**Issue by LemonU-mcmaster** [Dharakverma/vehicle_control_system#3]
SR1 and SR3 do kind of overlap. Specifically, SR1 sounds like a superset of SR3.

**Comment by smiths** [comment]
@LemonU-mcmaster, please create a separate issue for each of your issues.  :smile:

**Comment by LemonU-mcmaster** [comment]
> @LemonU-mcmaster, please create a separate issue for each of your issues. 😄

Thanks for the notice. I've divided them into two issues.

**Comment by Dharakverma** [comment]
There is no SR3.

**Comment by abhishekmagdum** [comment]
SR3 does not exist. I assume you mean the two separate SR2's? 

We've separated them since they affect different subsystems. One can brown out the accumulator, while the other affects the internal temperature, which is a much bigger issue (safety).
