### ISSUE TITLE
Team31 Review: Unit Tests: Minimal Traceability Between Test Cases and Requirements

### ISSUE THREAD

**Issue by atunney** [Dharakverma/vehicle_control_system#5]
In section 5 of the VnV plan, there is minimal traceability to test cases and their functional requirements. I then realized I was looking at the Unit Testing section and not the System Test Description section. It may have been better to leave the Unit Testing section out of the document for this initial revision since there are not any tests that can be traced back to requirements and as a reader I was a bit confused when the traceability section was filled out but there were not any tests to trace yet. This would be also better suited as a table like section 4.3.

**Comment by Dharakverma** [comment]
Agreed, but since that section is required for a future deliverable, we will leave it in the document for now. Sorry for the confusion.
